version: '3'

services:
    webservergo:
        build: .
        ports: 
            - 3000:8080
    nginx:
        image: nginx
        volumes: 
            - ./nginx:/usr/share/nginx/html
        ports:
            - 8080:80